name: Packages
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - package.json
      - yarn.lock
      - .yarn/cache
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  cache:
    name: Check Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: yarn install --immutable --check-cache
  review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v2
