name: Publish
on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next
      - next-major
      - '*.*.x'
      - '*.x'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn build
      - run: yarn publish
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          HUSKY_SKIP_HOOKS: '1'
